get:
  summary: product
  parameters:
    - name: XDEBUG_SESSION_START
      in: query
      required: false
      schema:
        type: string
        example: "XDEBUG_SESSION_START"
      description: "Debug session trigger"
    - name: barcode
      in: query
      required: false
      schema:
        type: string
        example: "2137"
      description: "Barcode"
  security:
    - bearerAuth: []
  responses:
    '200':
      description: Successful
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: string
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
